### ISSUE TITLE
neoscan kernel pid terminated while not operating network for a while

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo-scan#207]
I had neo-local just running for a while in my background without interacting with the privatenet network and it ended up throwing the below error and shutting down. I figured I'd drop it here to judge
```
neo-scan                | 2018-06-03 17:42:20.919 [warn] [neoscan@127.0.0.1] %HTTPoison.Error{id: nil, reason: :timeout} http://neo-nodes:30335
neo-scan                | 2018-06-03 17:42:20.920 [warn] [neoscan@127.0.0.1] %HTTPoison.Error{id: nil, reason: :timeout} http://neo-nodes:30334
neo-scan                | 2018-06-03 17:42:20.958 [error] [neoscan@127.0.0.1] Task #PID<0.8013.3> started from NeoscanSync.Producer terminating
neo-scan                | ** (MatchError) no match of right hand side value: nil
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:112: NeoscanSync.Producer.get_block_by_height/2
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:68: NeoscanSync.Producer.cross_check/1
neo-scan                |     (elixir) lib/task/supervised.ex:88: Task.Supervised.do_apply/2
neo-scan                |     (elixir) lib/task/supervised.ex:38: Task.Supervised.reply/5
neo-scan                |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan                | Function: #Function<6.94496139/0 in NeoscanSync.Producer.pmap/3>
neo-scan                |     Args: []
neo-scan                |
neo-scan                | =CRASH REPORT==== 3-Jun-2018::17:42:20 ===
neo-scan                |   crasher:
neo-scan                |     initial call: Elixir.NeoscanSync.Producer:'-pmap/3-fun-3-'/0
neo-scan                |     pid: <0.8013.3>
neo-scan                |     registered_name: []
neo-scan                |     exception exit: {{badmatch,nil},
neo-scan                |                      [{'Elixir.NeoscanSync.Producer',get_block_by_height,2,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,112}]},
neo-scan                |                       {'Elixir.NeoscanSync.Producer',cross_check,1,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,68}]},
neo-scan                |                       {'Elixir.Task.Supervised',do_apply,2,
neo-scan                |                           [{file,"lib/task/supervised.ex"},{line,88}]},
neo-scan                |                       {'Elixir.Task.Supervised',reply,5,
neo-scan                |                           [{file,"lib/task/supervised.ex"},{line,38}]},
neo-scan                |                       {proc_lib,init_p_do_apply,3,
neo-scan                |                           [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |       in function  'Elixir.Task.Supervised':exit/4 (lib/task/supervised.ex, line 121)
neo-scan                |       in call from 'Elixir.Task.Supervised':reply/5 (lib/task/supervised.ex, line 38)
neo-scan                |     ancestors: ['Elixir.NeoscanSync.Producer',
neo-scan                |                   'Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |     message_queue_len: 0
neo-scan                |     messages: []
neo-scan                |     links: [<0.6004.3>]
neo-scan                |     dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.8.15449617>,
neo-scan                |                                 next => #Fun<rand.5.15449617>,type => exrop,
neo-scan                |                                 uniform => #Fun<rand.6.15449617>,
neo-scan                |                                 uniform_n => #Fun<rand.7.15449617>,
neo-scan                |                                 weak_low_bits => 1},
neo-scan                |                               [61079872269106283|111648622808860366]}}]
neo-scan                |     trap_exit: false
neo-scan                |     status: running
neo-scan                |     heap_size: 1598
neo-scan                |     stack_size: 27
neo-scan                |     reductions: 119442
neo-scan                |   neighbours:
neo-scan                |     neighbour:
neo-scan                |       pid: <0.6004.3>
neo-scan                |       registered_name: 'Elixir.NeoscanSync.Producer'
neo-scan                |       initial call: Elixir.GenStage:init/1
neo-scan                |       current_function: {'Elixir.Task',yield,2}
neo-scan                |       ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |       message_queue_len: 0
neo-scan                |       links: [<0.1863.0>,<0.8013.3>]
neo-scan                |       trap_exit: false
neo-scan                |       status: waiting
neo-scan                |       heap_size: 987
neo-scan                |       stack_size: 43
neo-scan                |       reductions: 12418
neo-scan                |       current_stacktrace: [{'Elixir.Task',yield,2,[{file,"lib/task.ex"},{line,578}]},
neo-scan                |                   {'Elixir.NeoscanSync.Producer','-pmap/3-fun-2-',2,
neo-scan                |                       [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                        {line,57}]},
neo-scan                |                   {'Elixir.Enum','-map/2-lists^map/1-0-',2,
neo-scan                |                       [{file,"lib/enum.ex"},{line,1294}]},
neo-scan                |                   {'Elixir.Enum','-map/2-lists^map/1-0-',2,
neo-scan                |                       [{file,"lib/enum.ex"},{line,1294}]},
neo-scan                |                   {'Elixir.NeoscanSync.Producer',pmap,3,
neo-scan                |                       [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                        {line,57}]},
neo-scan                |                   {'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                       [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                        {line,48}]},
neo-scan                |                   {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                       [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                        {line,29}]},
neo-scan                |                   {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                       [{file,"lib/gen_stage.ex"},{line,2188}]}]
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:21 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    child_terminated
neo-scan                |      Reason:     {{badmatch,nil},
neo-scan                |                   [{'Elixir.NeoscanSync.Producer',get_block_by_height,2,
neo-scan                |                        [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                         {line,112}]},
neo-scan                |                    {'Elixir.NeoscanSync.Producer',cross_check,1,
neo-scan                |                        [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                         {line,68}]},
neo-scan                |                    {'Elixir.Task.Supervised',do_apply,2,
neo-scan                |                        [{file,"lib/task/supervised.ex"},{line,88}]},
neo-scan                |                    {'Elixir.Task.Supervised',reply,5,
neo-scan                |                        [{file,"lib/task/supervised.ex"},{line,38}]},
neo-scan                |                    {proc_lib,init_p_do_apply,3,
neo-scan                |                        [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |      Offender:   [{pid,<0.6004.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Producer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Producer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
notifications-server    | [I 180603 17:42:22 _observer:131] "172.18.0.5" - - [03/Jun/2018:17:42:20 +0000] "GET /v1/tokens HTTP/1.1" 200 121 "-" "hackney/1.11.0"
notifications-server    | 2018-06-03 17:42:22+0000 [-] "172.18.0.5" - - [03/Jun/2018:17:42:20 +0000] "GET /v1/tokens HTTP/1.1" 200 121 "-" "hackney/1.11.0"
neo-scan                | 2018-06-03 17:42:23.227 [error] [neoscan@127.0.0.1] GenServer NeoscanSync.Producer terminating
neo-scan                | ** (ArithmeticError) bad argument in arithmetic expression
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:45: NeoscanSync.Producer.evaluate/3
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:29: NeoscanSync.Producer.do_handle_demand/2
neo-scan                |     (gen_stage) lib/gen_stage.ex:2205: GenStage.noreply_callback/3
neo-scan                |     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
neo-scan                |     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
neo-scan                |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan                | Last message: {:"$gen_producer", {#PID<0.8063.3>, #Reference<0.859103628.3322150913.108120>}, {:ask, 150}}
neo-scan                |
neo-scan                | =CRASH REPORT==== 3-Jun-2018::17:42:23 ===
neo-scan                |   crasher:
neo-scan                |     initial call: Elixir.GenStage:init/1
neo-scan                |     pid: <0.8062.3>
neo-scan                |     registered_name: 'Elixir.NeoscanSync.Producer'
neo-scan                |     exception error: an error occurred when evaluating an arithmetic expression
neo-scan                |       in function  'Elixir.NeoscanSync.Producer':evaluate/3 (lib/neoscan_sync/genstage/producer.ex, line 45)
neo-scan                |       in call from 'Elixir.NeoscanSync.Producer':do_handle_demand/2 (lib/neoscan_sync/genstage/producer.ex, line 29)
neo-scan                |       in call from 'Elixir.GenStage':noreply_callback/3 (lib/gen_stage.ex, line 2205)
neo-scan                |       in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
neo-scan                |       in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
neo-scan                |     ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |     message_queue_len: 0
neo-scan                |     messages: []
neo-scan                |     links: [<0.1863.0>]
neo-scan                |     dictionary: []
neo-scan                |     trap_exit: false
neo-scan                |     status: running
neo-scan                |     heap_size: 987
neo-scan                |     stack_size: 27
neo-scan                |     reductions: 405
neo-scan                |   neighbours:
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:23 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    child_terminated
neo-scan                |      Reason:     {badarith,
neo-scan                |                      [{'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,45}]},
neo-scan                |                       {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,29}]},
neo-scan                |                       {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                           [{file,"lib/gen_stage.ex"},{line,2205}]},
neo-scan                |                       {gen_server,try_dispatch,4,
neo-scan                |                           [{file,"gen_server.erl"},{line,616}]},
neo-scan                |                       {gen_server,handle_msg,6,
neo-scan                |                           [{file,"gen_server.erl"},{line,686}]},
neo-scan                |                       {proc_lib,init_p_do_apply,3,
neo-scan                |                           [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |      Offender:   [{pid,<0.8062.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Producer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Producer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
notifications-server    | [I 180603 17:42:23 threading:864] [PrivateNet] Block 21567 / 21567
neo-scan                | 2018-06-03 17:42:23.997 [error] [neoscan@127.0.0.1] GenServer NeoscanSync.Producer terminating
neo-scan                | ** (ArithmeticError) bad argument in arithmetic expression
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:45: NeoscanSync.Producer.evaluate/3
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:29: NeoscanSync.Producer.do_handle_demand/2
neo-scan                |     (gen_stage) lib/gen_stage.ex:2205: GenStage.noreply_callback/3
neo-scan                |     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
neo-scan                |     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
neo-scan                |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan                | Last message: {:"$gen_producer", {#PID<0.8065.3>, #Reference<0.859103628.3322150913.108137>}, {:ask, 150}}
neo-scan                |
neo-scan                | =CRASH REPORT==== 3-Jun-2018::17:42:23 ===
neo-scan                |   crasher:
neo-scan                |     initial call: Elixir.GenStage:init/1
neo-scan                |     pid: <0.8064.3>
neo-scan                |     registered_name: 'Elixir.NeoscanSync.Producer'
neo-scan                |     exception error: an error occurred when evaluating an arithmetic expression
neo-scan                |       in function  'Elixir.NeoscanSync.Producer':evaluate/3 (lib/neoscan_sync/genstage/producer.ex, line 45)
neo-scan                |       in call from 'Elixir.NeoscanSync.Producer':do_handle_demand/2 (lib/neoscan_sync/genstage/producer.ex, line 29)
neo-scan                |       in call from 'Elixir.GenStage':noreply_callback/3 (lib/gen_stage.ex, line 2205)
neo-scan                |       in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
neo-scan                |       in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
neo-scan                |     ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |     message_queue_len: 0
neo-scan                |     messages: []
neo-scan                |     links: [<0.1863.0>]
neo-scan                |     dictionary: []
neo-scan                |     trap_exit: false
neo-scan                |     status: running
neo-scan                |     heap_size: 987
neo-scan                |     stack_size: 27
neo-scan                |     reductions: 405
neo-scan                |   neighbours:
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    child_terminated
neo-scan                |      Reason:     {badarith,
neo-scan                |                      [{'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,45}]},
neo-scan                |                       {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,29}]},
neo-scan                |                       {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                           [{file,"lib/gen_stage.ex"},{line,2205}]},
neo-scan                |                       {gen_server,try_dispatch,4,
neo-scan                |                           [{file,"gen_server.erl"},{line,616}]},
neo-scan                |                       {gen_server,handle_msg,6,
neo-scan                |                           [{file,"gen_server.erl"},{line,686}]},
neo-scan                |                       {proc_lib,init_p_do_apply,3,
neo-scan                |                           [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |      Offender:   [{pid,<0.8064.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Producer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Producer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
neo-scan                | 2018-06-03 17:42:24.089 [info] [neoscan@127.0.0.1] GenStage consumer NeoscanSync.Consumer is stopping after receiving cancel from producer #PID<0.8064.3> with reason: {:badarith, [{NeoscanSync.Producer, :evaluate, 3, [file: 'lib/neoscan_sync/genstage/producer.ex', line: 45]}, {NeoscanSync.Producer, :do_handle_demand, 2, [file: 'lib/neoscan_sync/genstage/producer.ex', line: 29]}, {GenStage, :noreply_callback, 3, [file: 'lib/gen_stage.ex', line: 2205]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}
neo-scan                |
neo-scan                | 2018-06-03 17:42:24.099 [error] [neoscan@127.0.0.1] GenServer NeoscanSync.Consumer terminating
neo-scan                | ** (ArithmeticError) bad argument in arithmetic expression
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:45: NeoscanSync.Producer.evaluate/3
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:29: NeoscanSync.Producer.do_handle_demand/2
neo-scan                |     (gen_stage) lib/gen_stage.ex:2205: GenStage.noreply_callback/3
neo-scan                |     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
neo-scan                |     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
neo-scan                |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan                | Last message: {:DOWN, #Reference<0.859103628.3322150913.108137>, :process, #PID<0.8064.3>, {:badarith, [{NeoscanSync.Producer, :evaluate, 3, [file: 'lib/neoscan_sync/genstage/producer.ex', line: 45]}, {NeoscanSync.Producer, :do_handle_demand, 2, [file: 'lib/neoscan_sync/genstage/producer.ex', line: 29]}, {GenStage, :noreply_callback, 3, [file: 'lib/gen_stage.ex', line: 2205]}, {:gen_server, :try_dispatch, 4, [file: 'gen_server.erl', line: 616]}, {:gen_server, :handle_msg, 6, [file: 'gen_server.erl', line: 686]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
neo-scan                |
neo-scan                | =CRASH REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |   crasher:
neo-scan                |     initial call: Elixir.GenStage:init/1
neo-scan                |     pid: <0.8065.3>
neo-scan                |     registered_name: 'Elixir.NeoscanSync.Consumer'
neo-scan                |     exception exit: {badarith,
neo-scan                |                         [{'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                              [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                               {line,45}]},
neo-scan                |                          {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                              [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                               {line,29}]},
neo-scan                |                          {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                              [{file,"lib/gen_stage.ex"},{line,2205}]},
neo-scan                |                          {gen_server,try_dispatch,4,
neo-scan                |                              [{file,"gen_server.erl"},{line,616}]},
neo-scan                |                          {gen_server,handle_msg,6,
neo-scan                |                              [{file,"gen_server.erl"},{line,686}]},
neo-scan                |                          {proc_lib,init_p_do_apply,3,
neo-scan                |                              [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |       in function  gen_server:handle_common_reply/8 (gen_server.erl, line 726)
neo-scan                |     ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |     message_queue_len: 0
neo-scan                |     messages: []
neo-scan                |     links: []
neo-scan                |     dictionary: []
neo-scan                |     trap_exit: false
neo-scan                |     status: running
neo-scan                |     heap_size: 610
neo-scan                |     stack_size: 27
neo-scan                |     reductions: 401
neo-scan                |   neighbours:
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    shutdown_error
neo-scan                |      Reason:     {badarith,
neo-scan                |                      [{'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,45}]},
neo-scan                |                       {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,29}]},
neo-scan                |                       {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                           [{file,"lib/gen_stage.ex"},{line,2205}]},
neo-scan                |                       {gen_server,try_dispatch,4,
neo-scan                |                           [{file,"gen_server.erl"},{line,616}]},
neo-scan                |                       {gen_server,handle_msg,6,
neo-scan                |                           [{file,"gen_server.erl"},{line,686}]},
neo-scan                |                       {proc_lib,init_p_do_apply,3,
neo-scan                |                           [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |      Offender:   [{pid,<0.8065.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Consumer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Consumer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
neo-scan                |
neo-scan                | =CRASH REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |   crasher:
neo-scan                |     initial call: Elixir.GenStage:init/1
neo-scan                |     pid: <0.8066.3>
neo-scan                |     registered_name: 'Elixir.NeoscanSync.Producer'
neo-scan                |     exception error: an error occurred when evaluating an arithmetic expression
neo-scan                |       in function  'Elixir.NeoscanSync.Producer':evaluate/3 (lib/neoscan_sync/genstage/producer.ex, line 45)
neo-scan                |       in call from 'Elixir.NeoscanSync.Producer':do_handle_demand/2 (lib/neoscan_sync/genstage/producer.ex, line 29)
neo-scan                |       in call from 'Elixir.GenStage':noreply_callback/3 (lib/gen_stage.ex, line 2205)
neo-scan                |       in call from gen_server:try_dispatch/4 (gen_server.erl, line 616)
neo-scan                |       in call from gen_server:handle_msg/6 (gen_server.erl, line 686)
neo-scan                |     ancestors: ['Elixir.NeoscanSync.Supervisor',<0.1862.0>]
neo-scan                |     message_queue_len: 0
neo-scan                |     messages: []
neo-scan                |     links: [<0.1863.0>]
neo-scan                |     dictionary: []
neo-scan                |     trap_exit: false
neo-scan                |     status: running
neo-scan                |     heap_size: 987
neo-scan                |     stack_size: 27
neo-scan                |     reductions: 405
neo-scan                |   neighbours:
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    child_terminated
neo-scan                |      Reason:     {badarith,
neo-scan                |                      [{'Elixir.NeoscanSync.Producer',evaluate,3,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,45}]},
neo-scan                |                       {'Elixir.NeoscanSync.Producer',do_handle_demand,2,
neo-scan                |                           [{file,"lib/neoscan_sync/genstage/producer.ex"},
neo-scan                |                            {line,29}]},
neo-scan                |                       {'Elixir.GenStage',noreply_callback,3,
neo-scan                |                           [{file,"lib/gen_stage.ex"},{line,2205}]},
neo-scan                |                       {gen_server,try_dispatch,4,
neo-scan                |                           [{file,"gen_server.erl"},{line,616}]},
neo-scan                |                       {gen_server,handle_msg,6,
neo-scan                |                           [{file,"gen_server.erl"},{line,686}]},
neo-scan                |                       {proc_lib,init_p_do_apply,3,
neo-scan                |                           [{file,"proc_lib.erl"},{line,247}]}]}
neo-scan                |      Offender:   [{pid,<0.8066.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Producer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Producer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
neo-scan                |
neo-scan                | =SUPERVISOR REPORT==== 3-Jun-2018::17:42:24 ===
neo-scan                |      Supervisor: {local,'Elixir.NeoscanSync.Supervisor'}
neo-scan                |      Context:    shutdown
neo-scan                |      Reason:     reached_max_restart_intensity
neo-scan                |      Offender:   [{pid,<0.8066.3>},
neo-scan                |                   {id,'Elixir.NeoscanSync.Producer'},
neo-scan                |                   {mfargs,{'Elixir.NeoscanSync.Producer',start_link,[]}},
neo-scan                |                   {restart_type,permanent},
neo-scan                |                   {shutdown,5000},
neo-scan                |                   {child_type,worker}]
neo-scan                |
neo-scan                | 2018-06-03 17:42:24.290 [error] [neoscan@127.0.0.1] GenServer NeoscanSync.Producer terminating
neo-scan                | ** (ArithmeticError) bad argument in arithmetic expression
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:45: NeoscanSync.Producer.evaluate/3
neo-scan                |     (neoscan_sync) lib/neoscan_sync/genstage/producer.ex:29: NeoscanSync.Producer.do_handle_demand/2
neo-scan                |     (gen_stage) lib/gen_stage.ex:2205: GenStage.noreply_callback/3
neo-scan                |     (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
neo-scan                |     (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
neo-scan                |     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan                | Last message: {:"$gen_producer", {#PID<0.8067.3>, #Reference<0.859103628.3319791618.96452>}, {:ask, 150}}
notifications-server    | [I 180603 17:42:24 _observer:131] "172.18.0.5" - - [03/Jun/2018:17:42:24 +0000] "GET /v1/tokens HTTP/1.1" 200 121 "-" "hackney/1.11.0"
notifications-server    | 2018-06-03 17:42:24+0000 [-] "172.18.0.5" - - [03/Jun/2018:17:42:24 +0000] "GET /v1/tokens HTTP/1.1" 200 121 "-" "hackney/1.11.0"
neo-scan                | 2018-06-03 17:42:26.120 [info] [neoscan@127.0.0.1] Application neoscan_sync exited: shutdown
neo-scan                | {"Kernel pid terminated",application_controller,"{application_terminated,neoscan_sync,shutdown}"}
neo-scan                | Kernel pid terminated (application_controller) ({application_terminated,neoscan_sync,shutdown})
neo-scan                |
neo-scan                | Crash dump is being written to: erl_crash.dump...done
neo-scan exited with code 1
```

**Comment by lucianoengel** [comment]
Your local nodes are timing out.
________________________________

**Comment by ixje** [comment]
Yeah I noticed (not sure why). As far as I could tell neo-scan doesn't handle that case gracefully and crashes. I figured you might want to know about that so it can be addressed, or if you don't want to address that feel free to close the issue :)

**Comment by lucianoengel** [comment]
Yes, thanks! In the latest build that should be fixed already I think.
________________________________

**Comment by adrienmo** [comment]
@ixje This should be resolved in the latest version, I am closing this issue now, feel free to reopen if you still have an issue after update.
