### ISSUE TITLE
MINNOR ISSUE: docker api and sync only working if db container is named postgres

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#357]
First of all, I would like to congratulate all involved in the project for the great improvements.

The system is much more stable and faster!

I am just having a minnor issue using the new `api` and `sync` dockers together with the `postgres` container.
My postgres container should exactly have the name "postgres".
Otherwise,
```
2018-10-15 22:47:03.294 [error] [neoscan_sync@127.0.0.1] Postgrex.Protocol (#PID<0.1286.0>) failed to connect: ** (DBConnection.ConnectionError) tcp connect (postgres:5432): non-existing domain - :nxdomain
2018-10-15 22:47:03.615 [info] [neoscan_sync@127.0.0.1] Application neoscan_sync exited: NeoscanSync.Application.start(:normal, []) returned an error: shutdown: failed to start child: NeoscanSync.Syncer
    ** (EXIT) an exception was raised:
        ** (DBConnection.ConnectionError) connection not available because of disconnection
            (db_connection) lib/db_connection.ex:934: DBConnection.checkout/2
            (db_connection) lib/db_connection.ex:750: DBConnection.run/3
            (db_connection) lib/db_connection.ex:592: DBConnection.prepare_execute/4
            (ecto) lib/ecto/adapters/postgres/connection.ex:86: Ecto.Adapters.Postgres.Connection.execute/4
            (ecto) lib/ecto/adapters/sql.ex:256: Ecto.Adapters.SQL.sql_call/6
            (ecto) lib/ecto/adapters/sql.ex:198: Ecto.Adapters.SQL.query!/5
            (neoscan) lib/neoscan/blocks/blocks.ex:108: Neoscan.Blocks.get_missing_block_indexes/0
            (neoscan_sync) lib/neoscan_sync/syncer.ex:22: NeoscanSync.Syncer.init/1
{"Kernel pid terminated",application_controller,"{application_start_failure,neoscan_sync,{{shutdown,{failed_to_start_child,'Elixir.NeoscanSync.Syncer',{#{'__exception__' => true,'__struct__' => 'Elixir.DBConnection.ConnectionError',message => <<\"connection not available because of disconnection\">>},[{'Elixir.DBConnection',checkout,2,[{file,\"lib/db_connection.ex\"},{line,934}]},{'Elixir.DBConnection',run,3,[{file,\"lib/db_connection.ex\"},{line,750}]},{'Elixir.DBConnection',prepare_execute,4,[{file,\"lib/db_connection.ex\"},{line,592}]},{'Elixir.Ecto.Adapters.Postgres.Connection',execute,4,[{file,\"lib/ecto/adapters/postgres/connection.ex\"},{line,86}]},{'Elixir.Ecto.Adapters.SQL',sql_call,6,[{file,\"lib/ecto/adapters/sql.ex\"},{line,256}]},{'Elixir.Ecto.Adapters.SQL','query!',5,[{file,\"lib/ecto/adapters/sql.ex\"},{line,198}]},{'Elixir.Neoscan.Blocks',get_missing_block_indexes,0,[{file,\"lib/neoscan/blocks/blocks.ex\"},{line,108}]},{'Elixir.NeoscanSync.Syncer',init,1,[{file,\"lib/neoscan_sync/syncer.ex\"},{line,22}]}]}}},{'Elixir.NeoscanSync.Application',start,[normal,[]]}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,neoscan_sync,{{shutdown,{failed_to_start_child,'Elixir.NeoscanSync.Syncer',{#{'__exception__' => true,'__struct__' => 'Elixir

Crash dump is being written to: erl_crash.dump...done
```

Do you think that it could be done as a parameter of the enviroment?

Thank you,

**Comment by adrienmo** [comment]
Hi @vncoelho, glad you like it. I am not sure of your setup, but it is already the case, If you look at the neo-local setup, you can see: https://github.com/CityOfZion/neo-local/blob/master/docker-compose.yml#L53

You just need to adjust this parameter to whatever hostname has your postgres container

**Comment by vncoelho** [comment]
In fact, I used this compose to update ours.

Thanks for the tips, I updated to `DB_HOSTNAME: eco-neo-scan-postgresql-running`. Solved.
