### ISSUE TITLE
NEO Scan fail in PrivateNet

### ISSUE THREAD

**Issue by im-kulikov** [CityOfZion/neo-scan#394]
```
neo-scan_1   | 2019-02-01 11:42:55.118 [warn] [nonode@nohost] Http error {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\
n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.4.6 (Ubuntu)</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.4.6 (Ubuntu)"}, {"Date", "Fri, 01 Feb 2019 0
8:42:55 GMT"}, {"Content-Type", "text/html"}, {"Content-Length", "181"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/histominute?fsym=NEO&tsym=BTC&lim
it=1440&toTs=1549010575&aggregate=1&extraParams=neoscan", status_code: 502}}
neo-scan_1   | 2019-02-01 11:42:55.134 [warn] [nonode@nohost] Http error {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\
n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.10.3"}, {"Date", "Fri, 01 Feb 2019 08:42:55 GMT"}, {
"Content-Type", "text/html"}, {"Content-Length", "173"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/histominute?fsym=GAS&tsym=USD&limit=1440&toTs=154
9010575&aggregate=1&extraParams=neoscan", status_code: 502}}
neo-scan_1   | 2019-02-01 11:42:55.141 [warn] [nonode@nohost] Http error {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\
n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.10.3"}, {"Date", "Fri, 01 Feb 2019 08:42:55 GMT"}, {
"Content-Type", "text/html"}, {"Content-Length", "173"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/histominute?fsym=GAS&tsym=BTC&limit=1440&toTs=154
9010575&aggregate=1&extraParams=neoscan", status_code: 502}}
neo-scan_1   | 2019-02-01 11:42:55.146 [warn] [nonode@nohost] Http error {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r\
n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.10.3"}, {"Date", "Fri, 01 Feb 2019 08:42:55 GMT"}, {
"Content-Type", "text/html"}, {"Content-Length", "173"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/histominute?fsym=NEO&tsym=USD&limit=1440&toTs=154
9010575&aggregate=1&extraParams=neoscan", status_code: 502}}
neo-scan_1   | 2019-02-01 11:42:55.622 [info] [nonode@nohost] Application neoscan_monitor exited: NeoscanMonitor.Application.start(:normal, []) returned an error: shutdown: failed to start c
hild: NeoscanMonitor.Worker
neo-scan_1   |     ** (EXIT) an exception was raised:
neo-scan_1   |         ** (MatchError) no match of right hand side value: {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r
\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.10.3"}, {"Date", "Fri, 01 Feb 2019 08:42:55 GMT"},
{"Content-Type", "text/html"}, {"Content-Length", "173"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=NEO&tsyms=BTC", status_code
: 502}}
neo-scan_1   |             (neoprice) lib/neoprice/cryptocompare/api.ex:23: Neoprice.Cryptocompare.Api.last_price_full/2
neo-scan_1   |             (neoscan_monitor) lib/neoscan_monitor/monitor/worker.ex:45: NeoscanMonitor.Worker.init/1
neo-scan_1   |             (stdlib) gen_server.erl:365: :gen_server.init_it/2
neo-scan_1   |             (stdlib) gen_server.erl:333: :gen_server.init_it/6
neo-scan_1   |             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
neo-scan_1   | ** (Mix) Could not start application neoscan_monitor: NeoscanMonitor.Application.start(:normal, []) returned an error: shutdown: failed to start child: NeoscanMonitor.Worker

neo-scan_1   |     ** (EXIT) an exception was raised:
neo-scan_1   |         ** (MatchError) no match of right hand side value: {:ok, %HTTPoison.Response{body: "<html>\r\n<head><title>502 Bad Gateway</title></head>\r\n<body bgcolor=\"white\">\r
\n<center><h1>502 Bad Gateway</h1></center>\r\n<hr><center>nginx/1.10.3</center>\r\n</body>\r\n</html>\r\n", headers: [{"Server", "nginx/1.10.3"}, {"Date", "Fri, 01 Feb 2019 08:42:55 GMT"},
{"Content-Type", "text/html"}, {"Content-Length", "173"}, {"Connection", "keep-alive"}], request_url: "https://min-api.cryptocompare.com/data/pricemultifull?fsyms=NEO&tsyms=BTC", status_code
: 502}}
neo-scan_1   |             (neoprice) lib/neoprice/cryptocompare/api.ex:23: Neoprice.Cryptocompare.Api.last_price_full/2
neo-scan_1   |             (neoscan_monitor) lib/neoscan_monitor/monitor/worker.ex:45: NeoscanMonitor.Worker.init/1
neo-scan_1   |             (stdlib) gen_server.erl:365: :gen_server.init_it/2
neo-scan_1   |             (stdlib) gen_server.erl:333: :gen_server.init_it/6
neo-scan_1   |             (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by fabwa** [comment]
Fixed with #392

**Comment by im-kulikov** [comment]
Can we add some settings to disable external requests?

**Comment by im-kulikov** [comment]
> the quickest way would be to change the container host, and redirect cryptocompare.com to 127.0.0.1

```extra_hosts:
 - "min-api.cryptocompare.com:127.0.0.1"
 - "www.cryptocompare.com:127.0.0.1"
```
> but that’s a bit hacky
