### ISSUE TITLE
NeoScan sometimes stop syncing

### ISSUE THREAD

**Issue by vncoelho** [CityOfZion/neo-scan#435]
```elixir
2019-11-06 21:15:32.706 [info] [neoscan_full@127.0.0.1] 0 ratio_insert, 0 ratio_download
2019-11-06 21:15:37.708 [info] [neoscan_full@127.0.0.1] 0.4 blocks/s, 0.4 transactions/s, 17152.0 download avg time, 21789.0 insert avg time
2019-11-06 21:15:37.708 [info] [neoscan_full@127.0.0.1] 0 ratio_insert, 0 ratio_download
2019-11-06 22:22:18.597 [info] [neoscan_full@127.0.0.1] JOIN "room:home" to NeoscanWeb.RoomChannel
  Transport:  Phoenix.Transports.WebSocket (2.0.0)
  Serializer:  Phoenix.Transports.V2.WebSocketSerializer
  Parameters: %{}
2019-11-06 22:22:18.597 [info] [neoscan_full@127.0.0.1] Replied room:home :ok
```

**Comment by vncoelho** [comment]
```elixir
2019-11-07 23:24:48.357 [info] [neoscan_full@127.0.0.1] 0.2 blocks/s, 0.2 transactions/s, 2267.0 download avg time, 2889.0 insert avg time
2019-11-07 23:24:48.357 [info] [neoscan_full@127.0.0.1] 0 ratio_insert, 0 ratio_download
2019-11-08 03:37:06.196 [info] [neoscan_full@127.0.0.1] tzdata release in place is from a file last modified Thu, 03 May 2018 23:55:14 GMT. Release file on server was last modified Wed, 11 Sep 2019 19:35:17 GMT.
2019-11-08 03:37:07.207 [error] [neoscan_full@127.0.0.1] GenServer :tzdata_release_updater terminating
** (FunctionClauseError) no function clause matching in Tzdata.Util.first_matching_weekday_in_month/4
    (tzdata) lib/tzdata/util.ex:73: Tzdata.Util.first_matching_weekday_in_month(1932, 4, 7, [])
    (tzdata) lib/tzdata/util.ex:329: Tzdata.Util.time_for_rule/2
    (tzdata) lib/tzdata/period_builder.ex:161: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:185: Tzdata.PeriodBuilder.calc_periods_for_year/9
    (tzdata) lib/tzdata/period_builder.ex:180: Tzdata.PeriodBuilder.calc_periods_for_year/9
Last message: :check_if_time_to_update
2019-11-08 04:04:18.631 [info] [neoscan_full@127.0.0.1] JOIN "room:home" to NeoscanWeb.RoomChannel
  Transport:  Phoenix.Transports.WebSocket (2.0.0)
  Serializer:  Phoenix.Transports.V2.WebSocketSerializer
  Parameters: %{}
2019-11-08 04:04:18.631 [info] [neoscan_full@127.0.0.1] Replied room:home :ok

```

**Comment by vncoelho** [comment]
Maybe it was because of its `NEO_SEEDS`

I was initializing like this on docker:

```yml
      NEO_SEEDS: "http://eco-neo-csharp-node1-running:30334;http://eco-neo-csharp-noderpc1-running:30333;http://eco-neo-csharp-noderpc1-running:30337"
```

And I saw like this on neo-local:
```yml
      NEO_SEEDS: >-
        http://eco-neo-csharp-node1-running:30334;http://eco-neo-csharp-noderpc1-running:30333;http://eco-neo-csharp-noderpc1-running:30337
```

Both ways should work, @adrienmo?
How can I check current peers of neo-scan?

**Comment by vncoelho** [comment]
![image](https://user-images.githubusercontent.com/17395762/68481946-3b436f80-0217-11ea-9ba9-53d57f327092.png)

I think this was the problem.
I just checked and saw that neoscan just connected to one of those NEO_SEEDS.

**Comment by vncoelho** [comment]
Fixed. It was my configuration problem.

I apologize for the inconvenience.
